package br.com.tavares.petcontrol.enums;

public enum EObjetosSubmetidos {

	OBJETO_SUBMETIDO_PESSOA("OBJETO_SUBMETIDO_PESSOA"),
	OBJETO_SUBMETIDO_ANIMAL("OBJETO_SUBMETIDO_ANIMAL"),
	OBJETO_SUBMETIDO_ANIMAL_PAI("OBJETO_SUBMETIDO_ANIMAL_PAI"),
	OBJETO_SUBMETIDO_ANIMAL_MAE("OBJETO_SUBMETIDO_ANIMAL_MAE"),
	OBJETO_SUBMETIDO_ANIMAIS("OBJETO_SUBMETIDO_ANIMAIS"),
	OBJETO_SUBMETIDO_PESSOAS("OBJETO_SUBMETIDO_PESSOAS"),
	OBJETO_SUBMETIDO_HISTORICO("OBJETO_SUBMETIDO_ADOCAO"),
	OBJETO_SUBMETIDO_LOGIN("OBJETO_SUBMETIDO_LOGIN");
	
	private final String value;

	EObjetosSubmetidos(String value) {
		this.value = value;
	}

	public String getValor() {
		return value;
	}

}
